---
abstract: '(EXPERIMENTAL) share directory'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: '0.98'
  Test::Requires: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Amon2-Plugin-ShareDir
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Amon2::Plugin::ShareDir:
    file: lib/Amon2/Plugin/ShareDir.pm
    version: v0.0.7
requires:
  Amon2: '3.76'
  Amon2::Util: '0'
  Amon2::Web: '0'
  File::ShareDir: '0'
  List::Util: '0'
  MRO::Compat: '0'
  if: '0'
  parent: '0'
  perl: '5.008005'
  version: '0'
resources:
  bugtracker: https://github.com/tokuhirom/Amon2-Plugin-ShareDir/issues
  homepage: https://github.com/tokuhirom/Amon2-Plugin-ShareDir
  repository: git://github.com/tokuhirom/Amon2-Plugin-ShareDir.git
version: v0.0.7
x_contributors:
  - 'tokuhirom <tokuhirom@gmail.com>'
